### ISSUE TITLE
When does new GTFS become available?

### ISSUE THREAD

**Issue by dfaulken** [umts/bojangles#60]
In particular, relative to when it actually goes into effect. Our current algorithm is "as soon as new files are available, download them and use them." Is that too naïve? Do we make files available before we actually need them?

That is, should our algorithm be (in ActiveRecord):

+ if there are no previously stored departures for today:
  + if there are new files:
    + download, parse, and use them
  + else:
    + there's a big problem

Whereas with the current behavior, we might download and use files that don't actually go into effect for a few days, and then bojangles would erroneously go quiet during the period between when the files are available and when that data goes into effect.

**Comment by werebus** [comment]
When we (Liza) are creating the GTFS feed file, we always start with "today" and go through Labor Day. In fact, I *think* that it might be a validation warning if the service starts in the future because many applications **do** use the "as soon as new files are available, download them and use them." algorithm.

Since the creation of a feed file is done by a human during their working hours, the feed you fetch in the wee hours of the morning will likely always be good for "yesterday" onward. And, there's no reason to delay using it; there's a (pretty small) chance that it might have corrections that are needed for "today'.

**Comment by dfaulken** [comment]
Great! Yep, you're right; it would be impossible to make corrections with the algorithm I proposed. Thanks!
